=encoding utf8

=head1 NAME

clrxasm - assemble program to binaries code

=head1 SYNOPSIS

clrxasm [-6Swa?] [-D SYM[=VALUE]] [-I PATH] [-o OUTFILE] [-b BINFORMAT]
[-g GPUDEVICE] [-A ARCH] [-t VERSION] [--defsym=SYM[=VALUE]] [--includePath=PATH]
[--output OUTFILE] [--binaryFormat=BINFORMAT] [--64bit] [--gpuType=GPUDEVICE]
[--arch=ARCH] [--driverVersion=VERSION] [--forceAddSymbols] [--noWarnings]
[--alternate] [--buggyFPLit] [--help] [--usage] [--version] [file...]

=head1 DESCRIPTION

This is CLRadeonExtender assembler. This assembler can assemble code for all Radeon GPU's
that based on the GCN1.0/1.1/1.2 architecture and it can generate AMD Catalyst
OpenCL binaries and the GalliumCompute OpenCL binaries. It is compatible with GNU as
and support the almost GNU as pseudo-operations (directives) including macros and
repetitions.

An assembler read source from many files. If no input file specified an assembler
will read source from standard input.

=head1 OPTIONS

Following options clrxasm can recognize:

=over 8

=item B<-D SYMBOL[=VALUE]>, B<--defsym=SYMBOL[=VALUE]>

Define symbol. Value is optional and if it is not given then assembler set 0 by default.
This option can be occurred many times to defining many symbols.

=item B<-I PATH>, B<--includePath=PATH>

Add an include path to search path list. Assembler begins search from current directory
and follows to next include paths.
This option can be occurred many times to adding many include paths.

=item B<-o FILENAME>, B<--output=FILENAME>

Set output file name. By default assembler write output to the 'a.out' file.

=item B<-b BINFORMAT>, B<--binaryFormat=BINFORMAT>

Set output binary format. This settings can be overriden in source code.
Assembler accepts following formats: 'amd', 'amdcl2', 'gallium', 'rocm', 'rawcode'.

=item B<-6>, B<--64bit>

Enable generating of the 64-bit binaries (only for AMD catalyst format).

=item B<-g GPUDEVICE>, B<--gpuType=GPUDEVICE>

Choose device type. Device type name is case-insensitive.
Currently is supported: 
CapeVerde, Pitcairn, Tahiti, Oland, Bonaire, Spectre, Spooky, Kalindi,
Hainan, Hawaii, Iceland, Tonga, Mullins, Fiji, Carrizo, Dummy, Goose, Horse, Stoney,
Ellesmere, and Baffin.

=item B<-A ARCH>, B<--arch=ARCH>

Choose device architecture. Architecture name is case-insensitive.
List of supported architectures:
GCN1.0, GCN1.1 and GCN1.2.

=item B<-t VERSION>, B<--driverVersion=VERSION>

Choose AMD Catalyst OpenCL driver version. Version can retrieved from clinfo program
that display field 'Driver version' where version is. Version is number in that form:
MajorVersion*100 + MinorVersion.

=item B<-S>, B<--forceAddSymbols>

Add all non-local symbols to binaries. By default any assembler does not add any symbols
to keep compatibility with original format.

=item B<-w>, B<--noWarnings>

Do not print all warnings.

=item B<-a>, B<--alternate>

Enable alternate macro syntax.

=item B<--buggyFPLit>

Choose old and buggy floating point literals rules (to 0.1.2 version) for compatibility.

=item B<-?>, B<--help>

Print help and list of the options.

=item B<--usage>

Print usage for this program

=item B<--version>

Print version

=back

=head1 ENVIRONMENT

Following environment variables impacts on assembler work:

=over 8

=item CLRX_AMDOCL_PATH

Path to AMDOCL (AMD OpenCL implementation) shared library
(libamdocl32.so, libamdocl64.so, amdocl32.dll or amdocl64.dll).

=back

=head1 RETURN VALUE

Returns zero if assembler succeeded, otherwise returns 1.

=head1 AUTHOR

Mateusz Szpakowski

=head1 SEE ALSO

clrxdisasm(1)
